blueprint:
  name: Toggle-button to control light
  description: This blueprint allows a button to toggle a light in Home Assistant
  domain: automation
  input:
    buttondevice:
      name: Knap
      description: Denne knap styrer lyset.
      selector:
        entity:
          filter:
            - domain: mqtt
    lightdevice:
      name: Lys
      description: Disse lamper styres.
      selector:
        target:
          entity:
            - domain: light
triggers:
  - domain: mqtt
    device_id: !buttondevice
    type: action
    subtype: off_top
    trigger: device

actions:
  - if:
      - condition: numeric_state
        entity_id: !lightdevice
        attribute: brightness
        above: 30
    then:
      - action: light.turn_off
        metadata: {}
        data: {}
        target:
          device_id: !lightdevice
    else:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_pct: 100
        target:
          device_id: !lightdevice
mode: single
