# Ikea Shortcut Button Blueprint for Home Assistant

blueprint:
  name: MQTT - IKEA TRÅDFRI Shortcut Button
  description: Home Assistant automation Blueprint for the TRÅDFRI Shortcut Button, supports single, double and long presses.
  domain: automation
  input:
    shortcut_button:
      name: Device
      description: Select a device...
      selector:
        device:
          integration: mqtt
    button_single:
      name: Single Click
      description: 'Single-Click action(s):'
      default: []
      selector:
        action: {}
    button_double:
      name: Double Click
      description: 'Double-Click action(s):'
      default: []
      selector:
        action: {}
    button_long:
      name: Long Press
      description: 'Long press action(s):'
      default: []
      selector:
        action: {}
mode: single
max_exceeded: silent
trigger:
- platform: event
  event_type: mqtt_event
  event_data:
    device_id: !input 'shortcut_button'
action:
- choose:
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.command == "on" }}'
    sequence: !input 'button_single'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.command == "off" }}'
    sequence: !input 'button_double'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.command == "move_with_on_off" }}'
    sequence: !input 'button_long'
