blueprint:
  name: Button control
  description: Turn a light on/off based on button press
  domain: automation
  input:
    button:
      name: Knap
      description: Denne knap styrer lyset.
      selector:
        entity:
          filter:
            - domain: device
            - device_class: mqtt
    target_light:
      name: Lys
      description: Disse lamper styres.
      selector:
        target:
          entity:
            - domain: light

triggers:
  - trigger: state
    entity_id: !input knap

actions:
  - action: >
      {% if trigger.to_state.state == "on" %}
        light.turn_on
      {% else %}
        light.turn_off
      {% endif %}
    target: !input target_light
