# Ikea Shortcut Button Blueprint for Home Assistant

blueprint:
  name: MQTT - IKEA TRÅDFRI Shortcut Button
  description: Home Assistant automation Blueprint for buttons.
  domain: automation
  input:
    button:
      name: Device
      description: Select a device...
      selector:
        device:
          integration: mqtt
    button_single:
      name: Single Click
      description: 'Single-Click action(s):'
      default: []
      selector:
        action: {}
mode: single
max_exceeded: silent
trigger:
- platform: event
  event_type: mqtt_event
  event_data:
    device_id: !input 'shortcut_button'
action:
- choose:
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.command == "on" }}'
